spec-version: 0.30.0
name: hackcell 
author: Patrick D. Elliott
maintainer: patrick.d.elliott@gmail.com
version: 0.1.0.0
license: BSD3

build-type: Simple

source-dirs: src
dependencies:
- { name: "base", version: '^>=4.13' }
- { name: "sdl2", version: '2.5.2.0' }
- { name: "vector" }

ghc-options: [-Wall,-threaded]
# default-extensions:
library: {}
executable:
  main: Main.hs
