spec-version: 0.30.0
name: hackcell 
author: Patrick D. Elliott
maintainer: patrick.d.elliott@gmail.com
version: 0.1.0.0
license: null 

build-type: Simple

data-dir: data
source-dirs: src
dependencies:
- { name: "base", version: '^>=4.13' }
- { name: "sdl2", version: '^>=2.5.2.0' }
- { name: "sdl2-image", version: '^>=2.0.0' }
- { name: "apecs", version: '^>=0.9.1' }
- { name: "grid", version: '^>=7.8.14' }
- { name: "microlens" }
- { name: "vector" }

ghc-options: [-Wall,-threaded]
# default-extensions:
library: {}
executable:
  main: Main.hs
